defaults: &defaults
  adapter: mysql
  encoding: utf8
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

development:
  database: photo_development
  <<: *defaults

test:
  database: photo_test
  <<: *defaults

production:
  database: photo_production
  <<: *defaults
